version: '3.8'

name: 'postgres_nestjs-final-test'

services:
  postgres:
    image: postgres:latest
    ports:
      - "24000:5432"
    environment:
      POSTGRES_DB: "nestjs-final-test-db"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/create-postgres-db.sql:/docker-entrypoint-initdb.d/create-postgres-db.sql

volumes:
  postgres_data:
